### Send GitHub push
POST http://localhost:8080/githubwebhook/
Content-Type: application/json

{
  "commits": [
    {
      "added": [
        "images/Test.png"
      ],
      "removed": [
      ],
      "modified": [
        "README.md"
      ]
    }
  ]
}

### Read Images
GET https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures

### Read Image
GET https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures('458f65ab820f2f21f0ae3fc744b75053df363648dbb1dcabf15f0d8014e910f4')/content

### Delete Image
DELETE https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures('8947778c698bed6d3da7dd81b670848580974e718c796575f1f64db2557d5ef4')

### Read Images
GET https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures

### Create Image
POST https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures
Accept: application/json
Content-Type: application/json

{ 
  "ID": "8947778c698bed6d3da7dd81b670848580974e718c796575f1f64db2557d5ef4"
}

### Upload Image
PUT https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures('8947778c698bed6d3da7dd81b670848580974e718c796575f1f64db2557d5ef4')/content
Content-Type: image/png

< ./Test.png

### Read Picture
GET https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures('8947778c698bed6d3da7dd81b670848580974e718c796575f1f64db2557d5ef4')/content

### Delete Picture
DELETE https://rcpduskkh8xe9q03cture-backend-srv.cfapps.eu10.hana.ondemand.com/media/Pictures('8947778c698bed6d3da7dd81b670848580974e718c796575f1f64db2557d5ef4')


### Send GitHub push to production
POST 	https://f983bf4f-59c6-4523-a939-1b9caa795140.ingress.live.faas-live.shoot.live.k8s-hana.ondemand.com/githubwebhook/
Content-Type: application/json

{
  "commits": [
    {
      "added": [
        "images/Test.png"
      ],
      "removed": [
      ],
      "modified": [
        "README.md"
      ]
    }
  ]
}

### Send GitHub push with png
POST http://localhost:8080/githubwebhook/
Content-Type: application/json

{
  "ref": "refs/heads/master",
  "before": "7e562fd258802bf1cfbfb935b8135a191fb470ae",
  "after": "edf917bc7fe24bc1fd9134ddd62c6a320457cf61",
  "repository": {
    "id": 225699081,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMjU2OTkwODE=",
    "name": "25daysofserverlessDay3",
    "full_name": "gregorwolf/25daysofserverlessDay3",
    "private": false,
    "owner": {
      "name": "gregorwolf",
      "email": "gregor.wolf@gmail.com",
      "login": "gregorwolf",
      "id": 2639535,
      "node_id": "MDQ6VXNlcjI2Mzk1MzU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2639535?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gregorwolf",
      "html_url": "https://github.com/gregorwolf",
      "followers_url": "https://api.github.com/users/gregorwolf/followers",
      "following_url": "https://api.github.com/users/gregorwolf/following{/other_user}",
      "gists_url": "https://api.github.com/users/gregorwolf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gregorwolf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gregorwolf/subscriptions",
      "organizations_url": "https://api.github.com/users/gregorwolf/orgs",
      "repos_url": "https://api.github.com/users/gregorwolf/repos",
      "events_url": "https://api.github.com/users/gregorwolf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gregorwolf/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/gregorwolf/25daysofserverlessDay3",
    "description": "25daysofserverless Day 3",
    "fork": false,
    "url": "https://github.com/gregorwolf/25daysofserverlessDay3",
    "forks_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/forks",
    "keys_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/teams",
    "hooks_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/hooks",
    "issue_events_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/issues/events{/number}",
    "events_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/events",
    "assignees_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/assignees{/user}",
    "branches_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/branches{/branch}",
    "tags_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/tags",
    "blobs_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/languages",
    "stargazers_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/stargazers",
    "contributors_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/contributors",
    "subscribers_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/subscribers",
    "subscription_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/subscription",
    "commits_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/contents/{+path}",
    "compare_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/merges",
    "archive_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/downloads",
    "issues_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/issues{/number}",
    "pulls_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/labels{/name}",
    "releases_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/releases{/id}",
    "deployments_url": "https://api.github.com/repos/gregorwolf/25daysofserverlessDay3/deployments",
    "created_at": 1575401369,
    "updated_at": "2019-12-03T19:32:44Z",
    "pushed_at": 1575487308,
    "git_url": "git://github.com/gregorwolf/25daysofserverlessDay3.git",
    "ssh_url": "git@github.com:gregorwolf/25daysofserverlessDay3.git",
    "clone_url": "https://github.com/gregorwolf/25daysofserverlessDay3.git",
    "svn_url": "https://github.com/gregorwolf/25daysofserverlessDay3",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "gregorwolf",
    "email": "gregor.wolf@gmail.com"
  },
  "sender": {
    "login": "gregorwolf",
    "id": 2639535,
    "node_id": "MDQ6VXNlcjI2Mzk1MzU=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/2639535?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gregorwolf",
    "html_url": "https://github.com/gregorwolf",
    "followers_url": "https://api.github.com/users/gregorwolf/followers",
    "following_url": "https://api.github.com/users/gregorwolf/following{/other_user}",
    "gists_url": "https://api.github.com/users/gregorwolf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gregorwolf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gregorwolf/subscriptions",
    "organizations_url": "https://api.github.com/users/gregorwolf/orgs",
    "repos_url": "https://api.github.com/users/gregorwolf/repos",
    "events_url": "https://api.github.com/users/gregorwolf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gregorwolf/received_events",
    "type": "User",
    "site_admin": false
  },
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/gregorwolf/25daysofserverlessDay3/compare/7e562fd25880...edf917bc7fe2",
  "commits": [
    {
      "id": "edf917bc7fe24bc1fd9134ddd62c6a320457cf61",
      "tree_id": "df1c3ced2e7e28cc59fa3df057886bb5ce859664",
      "distinct": true,
      "message": "Add first png",
      "timestamp": "2019-12-04T20:21:37+01:00",
      "url": "https://github.com/gregorwolf/25daysofserverlessDay3/commit/edf917bc7fe24bc1fd9134ddd62c6a320457cf61",
      "author": {
        "name": "Gregor Wolf",
        "email": "gregor.wolf@gmail.com",
        "username": "gregorwolf"
      },
      "committer": {
        "name": "Gregor Wolf",
        "email": "gregor.wolf@gmail.com",
        "username": "gregorwolf"
      },
      "added": [
        "images/Test.png"
      ],
      "removed": [
      ],
      "modified": [
        "README.md"
      ]
    }
  ],
  "head_commit": {
    "id": "edf917bc7fe24bc1fd9134ddd62c6a320457cf61",
    "tree_id": "df1c3ced2e7e28cc59fa3df057886bb5ce859664",
    "distinct": true,
    "message": "Add first png",
    "timestamp": "2019-12-04T20:21:37+01:00",
    "url": "https://github.com/gregorwolf/25daysofserverlessDay3/commit/edf917bc7fe24bc1fd9134ddd62c6a320457cf61",
    "author": {
      "name": "Gregor Wolf",
      "email": "gregor.wolf@gmail.com",
      "username": "gregorwolf"
    },
    "committer": {
      "name": "Gregor Wolf",
      "email": "gregor.wolf@gmail.com",
      "username": "gregorwolf"
    },
    "added": [
      "images/Test.png"
    ],
    "removed": [
    ],
    "modified": [
      "README.md"
    ]
  }
}